services:
  app:
    build: .
    container_name: mercadolibros_springboot
    mem_limit: 512m
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      JAVA_TOOL_OPTIONS: "-XX:MaxRAMPercentage=75.0"
      DB_URL: ${DB_URL:-jdbc:mysql://mysql:3306/mercadolibros_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8}
      DB_USERNAME: ${DB_USERNAME:-usuario}
      DB_PASSWORD: ${DB_PASSWORD:-usuario123}
    restart: always
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.4
    container_name: mercadolibros_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mercadolibros_db}
      MYSQL_USER: ${DB_USERNAME:-usuario}
      MYSQL_PASSWORD: ${DB_PASSWORD:-usuario123}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_0900_ai_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mercadolibros_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: ${PMA_USER:-root}
      PMA_PASSWORD: ${PMA_PASSWORD:-root}
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
