services:
  mysql:
    image: mysql:8.0
    container_name: mercadolibros_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mercadolibros_db
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mercadolibros_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
